package gdfumo

import io.circe._
import io.circe.generic.semiauto._
import datatype._

case class buffSkills(
  skillMaxLevel: Int,
  templateName: String,
  skillDisplayName: String,
  l: String,
  o: String,
  racialBonusRace: Option[String],
  skillDownBitmapName: Option[String],
  skillBaseDescription: Option[String],
  petBonusName: Option[String],
  skillUpBitmapName: Option[String],
  offensiveSlowFireModifier: Option[List[Int]],
  skillConnectionOff: Option[List[String]],
  skillConnectionOn: Option[List[String]],
  dispelFriendly: Option[BigDecimal],
  offensiveSlowColdChance: Option[BigDecimal],
  contagionMaxSpread: Option[BigDecimal],
  skillManaCostReduction: Option[BigDecimal],
  defensiveBlockAmountModifier: Option[BigDecimal],
  offensiveSlowLifeDurationModifier: Option[BigDecimal],
  offensiveSlowLightningXOR: Option[BigDecimal],
  defensiveTrap: Option[BigDecimal],
  offensivePierceMax: Option[BigDecimal],
  offensivePetrifyMin: Option[BigDecimal],
  offensiveProjectileFumbleMin: Option[BigDecimal],
  defensivePoisonDuration: Option[BigDecimal],
  racialBonusPercentDamage: Option[BigDecimal],
  offensiveSlowRunSpeedMin: Option[BigDecimal],
  offensivePhysicalModifier: Option[BigDecimal],
  defensiveSlowLifeLeach: Option[BigDecimal],
  offensiveSlowBleedingDurationMin: Option[BigDecimal],
  offensiveLightningModifier: Option[BigDecimal],
  retaliationPoisonMin: Option[BigDecimal],
  retaliationPoisonModifier: Option[BigDecimal],
  offensiveConfusionChance: Option[BigDecimal],
  skillTier: Option[BigDecimal],
  offensiveTotalResistanceReductionAbsoluteMin: Option[BigDecimal],
  isPetDisplayable: Option[BigDecimal],
  offensiveColdMax: Option[BigDecimal],
  offensiveGlobalChance: Option[BigDecimal],
  defensiveProtectionModifier: Option[BigDecimal],
  defensiveConfusion: Option[BigDecimal],
  offensiveFearMin: Option[BigDecimal],
  characterDodgePercent: Option[BigDecimal],
  characterDefensiveAbilityModifier: Option[BigDecimal],
  contagionRadius: Option[BigDecimal],
  defensiveFear: Option[BigDecimal],
  offensiveSlowFireDurationMin: Option[BigDecimal],
  contagionLimit: Option[BigDecimal],
  skillUltimateLevel: Option[BigDecimal],
  defensiveKnockdown: Option[BigDecimal],
  damageAbsorptionPercent: Option[BigDecimal],
  offensiveSlowColdXOR: Option[BigDecimal],
  defensiveAetherMaxResist: Option[BigDecimal],
  offensiveFumbleMin: Option[BigDecimal],
  characterLightRadius: Option[BigDecimal],
  defensiveLightningDuration: Option[BigDecimal],
  offensiveSlowRunSpeedDurationMin: Option[BigDecimal],
  offensiveSlowColdDurationMin: Option[BigDecimal],
  offensiveSlowPoisonDurationMin: Option[BigDecimal],
  characterHealIncreasePercent: Option[BigDecimal],
  retaliationLightningMax: Option[BigDecimal],
  defensiveFreeze: Option[BigDecimal],
  offensiveSlowFireXOR: Option[BigDecimal],
  defensiveColdDuration: Option[BigDecimal],
  retaliationFreezeChance: Option[BigDecimal],
  offensiveSlowLightningChance: Option[BigDecimal],
  retaliationConfusionChance: Option[BigDecimal],
  offensiveProjectileFumbleDurationMin: Option[BigDecimal],
  offensiveSlowFireGlobal: Option[BigDecimal],
  offensiveSlowColdGlobal: Option[BigDecimal],
  offensiveSlowPoisonDurationModifier: Option[BigDecimal],
  retaliationLightningMin: Option[BigDecimal],
  offensiveSlowTotalSpeedDurationMin: Option[BigDecimal],
  defensiveSleep: Option[BigDecimal],
  offensiveFumbleDurationMin: Option[BigDecimal],
  offensiveTotalResistanceReductionAbsoluteDurationMin: Option[BigDecimal],
  retaliationConfusionMin: Option[BigDecimal],
  offensivePetrifyChance: Option[BigDecimal],
  offensiveSlowLightningGlobal: Option[BigDecimal],
  offensivePhysicalReductionPercentDurationMin: Option[BigDecimal],
  defensiveBleedingDuration: Option[BigDecimal],
  defensiveFireDuration: Option[BigDecimal],
  hideFromUI: Option[BigDecimal],
  offensiveSlowLightningModifier: Option[BigDecimal],
  defensiveLifeDuration: Option[BigDecimal],
  offensivePoisonModifierChance: Option[BigDecimal],
  defensiveReflect: Option[BigDecimal],
  contagionInterval: Option[BigDecimal],
  defensiveStun: Option[BigDecimal],
  offensiveAetherMax: Option[BigDecimal],
  retaliationSlowPoisonDurationMin: Option[BigDecimal],
  offensivePhysicalMax: Option[BigDecimal],
  offensiveSlowColdDurationModifier: Option[BigDecimal],
  offensiveSlowFireChance: Option[BigDecimal],
  offensiveSlowLifeDurationMin: Option[BigDecimal],
  debufSkill: Option[BigDecimal],
  offensiveConfusionMin: Option[BigDecimal],
  retaliationFreezeMin: Option[BigDecimal],
  offensiveSlowLightningDurationMin: Option[BigDecimal],
  defensivePetrify: Option[BigDecimal],
  offensiveFireMax: Option[List[BigDecimal]],
  racialBonusAbsoluteDamage: Option[List[BigDecimal]],
  defensivePercentCurrentLife: Option[List[BigDecimal]],
  offensiveDamageMultModifier: Option[List[BigDecimal]],
  characterLifeModifier: Option[List[BigDecimal]],
  offensiveSlowFireMin: Option[List[BigDecimal]],
  offensiveFireModifier: Option[List[BigDecimal]],
  retaliationColdMax: Option[List[BigDecimal]],
  offensiveSlowLifeMin: Option[List[BigDecimal]],
  characterDeflectProjectile: Option[List[BigDecimal]],
  offensivePhysicalReductionPercentMin: Option[List[BigDecimal]],
  offensiveChaosModifier: Option[List[BigDecimal]],
  retaliationTotalDamageModifier: Option[List[BigDecimal]],
  retaliationPhysicalMax: Option[List[BigDecimal]],
  offensiveElementalMin: Option[List[BigDecimal]],
  retaliationSlowPoisonMin: Option[List[BigDecimal]],
  offensiveSlowTotalSpeedMin: Option[List[BigDecimal]],
  offensivePercentCurrentLifeMax: Option[List[BigDecimal]],
  retaliationColdMin: Option[List[BigDecimal]],
  offensiveSlowBleedingModifier: Option[List[BigDecimal]],
  offensiveTotalDamageReductionPercentMin: Option[List[BigDecimal]],
  offensiveCritDamageModifier: Option[List[BigDecimal]],
  retaliationPhysicalMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveSlowLightningMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveLifeModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveFireMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveColdModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterDefensiveAbility: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensiveFire: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  skillActiveDuration: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveChaosMax: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensivePoison: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterLifeRegen: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  skillCooldownTime: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensivePierce: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveTotalDamageReductionPercentDurationMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveSlowLifeModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveSlowColdMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensivePoisonModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveSlowPoisonModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterLifeRegenModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensivePierceMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterRunSpeedModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveAetherMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterSpellCastSpeedModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  skillTargetRadius: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterManaLimitReserve: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  skillLifeBonus: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensivePoisonMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensiveChaos: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveTotalDamageModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensivePercentCurrentLifeMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensiveAether: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveLifeLeechMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  skillManaCost: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveSlowPoisonMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveLifeMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  skillLifePercent: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensivePhysical: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveSlowBleedingMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveColdMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensiveLightning: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterTotalSpeedModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensivePhysicalMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensiveCold: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterAttackSpeedModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveChaosMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterOffensiveAbility: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveSlowColdModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensiveLife: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveLightningMin: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensiveBleeding: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveLifeMax: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  characterOffensiveAbilityModifier: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  defensiveElementalResistance: Option[AdtData2[BigDecimal, List[BigDecimal]]],
  offensiveLightningMax: Option[AdtData2[BigDecimal, List[BigDecimal]]]
)

object buffSkills {
  implicit val codecJson: Codec[buffSkills] = {
    val impl = deriveCodec[buffSkills]
    Codec.from(impl, impl.mapJson(_.dropNullValues))
  }

  val derived111: (En121[buffSkills], shapeless.HList) = En121.derived
}
