package gdfumo

import io.circe.{Codec, Decoder, Encoder, Json}
import io.circe.generic.JsonCodec
import io.circe.generic.semiauto.deriveCodec
import datatype.{ListOrItem, StringOrElse}

case class itemSkills_1(
  templateName: String,
  l: Option[String],
  offensiveSlowPoisonChance: Option[BigDecimal],
  timeBetweenAttacks: Option[BigDecimal],
  offensiveSlowColdChance: Option[BigDecimal],
  retaliationSlowPhysicalMin: Option[List[Int]],
  offensiveSlowManaLeachMin: Option[List[Int]],
  retaliationChaosMax: Option[List[Int]],
  retaliationLifeMin: Option[List[Int]],
  spawnObjects: Option[Map[String, Json]],
  retaliationStunChance: Option[List[Int]],
  racialBonusAbsoluteDamage: Option[List[Int]],
  retaliationLifeMax: Option[List[Int]],
  retaliationChaosMin: Option[List[Int]],
  petSkillName: Option[Map[String, StringOrElse[ListOrItem[BigDecimal]]]],
  offensivePhysicalChance: Option[List[Int]],
  dualRangedOnly: Option[BigDecimal],
  skillManaCostReduction: Option[BigDecimal],
  duration: Option[BigDecimal],
  projectileUsesAllDamage: Option[BigDecimal],
  onHitActivationChance: Option[BigDecimal],
  Sword: Option[BigDecimal],
  retaliationSlowAttackSpeedMin: Option[BigDecimal],
  offensiveElementalResistanceReductionPercentDurationMin: Option[BigDecimal],
  retaliationFireModifier: Option[BigDecimal],
  Ranged2h: Option[BigDecimal],
  offensivePetrifyMin: Option[BigDecimal],
  offensiveStunMax: Option[BigDecimal],
  offensiveSlowTotalSpeedGlobal: Option[BigDecimal],
  defensivePoisonDuration: Option[BigDecimal],
  skillBaseDescription: Option[String],
  racialBonusPercentDamage: Option[BigDecimal],
  offensiveDamageMultModifier: Option[BigDecimal],
  lifeDamageQualifier: Option[BigDecimal],
  thresholdDuration: Option[BigDecimal],
  canUseWhileMoving: Option[BigDecimal],
  retaliationDamageMultModifier: Option[BigDecimal],
  offensivePetrifyXOR: Option[BigDecimal],
  skillTier: Option[BigDecimal],
  cooldownTime: Option[BigDecimal],
  Axe2h: Option[BigDecimal],
  isPetDisplayable: Option[BigDecimal],
  skillChargeLevel: Option[BigDecimal],
  defensiveFire: Option[BigDecimal],
  offensiveGlobalChance: Option[BigDecimal],
  Dagger: Option[BigDecimal],
  defensiveAetherMaxResist: Option[BigDecimal],
  defensivePetrify: Option[BigDecimal],
  offensiveFreezeMin: Option[BigDecimal],
  offensiveSlowLifeDurationModifier: Option[BigDecimal],
  defensiveLightningMaxResist: Option[BigDecimal],
  defensiveTrap: Option[BigDecimal],
  offensiveSlowAttackSpeedDurationMin: Option[BigDecimal],
  defensiveLifeMaxResist: Option[BigDecimal],
  offensiveSlowLightningXOR: Option[BigDecimal],
  useResetsDuration: Option[BigDecimal],
  offensiveColdModifierChance: Option[BigDecimal],
  offensiveSlowPhysicalDurationModifier: Option[BigDecimal],
  defensiveDisruption: Option[BigDecimal],
  dualRangedOrAllRangedOnly: Option[BigDecimal],
  retaliationPhysicalModifier: Option[BigDecimal],
  defensiveFireMaxResist: Option[BigDecimal],
  racialBonusAbsoluteDefense: Option[BigDecimal],
  projectilePeriod: Option[BigDecimal],
  Offhand: Option[BigDecimal],
  defensiveSlowLifeLeach: Option[BigDecimal],
  offensiveSlowRunSpeedMin: Option[BigDecimal],
  offensiveElementalChance: Option[BigDecimal],
  petPadding: Option[BigDecimal],
  projectilePiercing: Option[BigDecimal],
  offensiveElementalResistanceReductionPercentMin: Option[BigDecimal],
  retaliationFearMin: Option[BigDecimal],
  startWidth: Option[BigDecimal],
  waveSource: Option[String],
  beamThickness: Option[BigDecimal],
  stunPeriod: Option[BigDecimal],
  defensiveChaosMaxResist: Option[BigDecimal],
  Spear2h: Option[BigDecimal],
  Axe: Option[BigDecimal],
  overwriteBaseSkill: Option[BigDecimal],
  sparkGap: Option[BigDecimal],
  offensiveFreezeChance: Option[BigDecimal],
  retaliationPoisonModifier: Option[BigDecimal],
  trackSpawns: Option[BigDecimal],
  offensiveSlowOffensiveAbilityXOR: Option[BigDecimal],
  defensiveColdMaxResist: Option[BigDecimal],
  offensiveSlowLightningDurationModifier: Option[BigDecimal],
  fxPakAlternate: Option[BigDecimal],
  offensiveSlowTotalSpeedXOR: Option[BigDecimal],
  maxRange: Option[BigDecimal],
  offensiveConfusionMax: Option[BigDecimal],
  offensiveAetherModifierChance: Option[BigDecimal],
  offensiveTotalResistanceReductionAbsoluteChance: Option[BigDecimal],
  explosionRadius: Option[BigDecimal],
  offensiveSlowLightningDurationMin: Option[BigDecimal],
  retaliationFreezeMin: Option[BigDecimal],
  characterMana: Option[BigDecimal],
  chaosDamageQualifier: Option[BigDecimal],
  characterLife: Option[BigDecimal],
  retaliationStunMin: Option[BigDecimal],
  delayMovement: Option[BigDecimal],
  skillChargeDuration: Option[BigDecimal],
  skillChargeTime: Option[BigDecimal],
  physicalDamageQualifier: Option[BigDecimal],
  defensiveAether: Option[BigDecimal],
  skillCooldownReductionChance: Option[BigDecimal],
  Sword2h: Option[BigDecimal],
  skillUltimateLevel: Option[BigDecimal],
  offensiveSlowBleedingDurationModifier: Option[BigDecimal],
  offensiveFireMax: Option[ListOrItem[BigDecimal]],
  projectileLaunchRotation: Option[ListOrItem[BigDecimal]],
  projectileExplosionRadius: Option[ListOrItem[BigDecimal]],
  offensiveSlowLightningMin: Option[ListOrItem[BigDecimal]],
  offensiveSlowFireDurationMin: Option[ListOrItem[BigDecimal]],
  offensivePierceMax: Option[ListOrItem[BigDecimal]],
  offensiveLifeModifier: Option[ListOrItem[BigDecimal]],
  defensivePercentCurrentLife: Option[ListOrItem[BigDecimal]],
  offensiveProjectileFumbleMin: Option[ListOrItem[BigDecimal]],
  offensiveSlowDefensiveAbilityDurationMin: Option[ListOrItem[BigDecimal]],
  offensiveFireMin: Option[ListOrItem[BigDecimal]],
  offensiveStunChance: Option[ListOrItem[BigDecimal]],
  offensivePoisonMax: Option[ListOrItem[BigDecimal]],
  conversionOutType2: Option[ListOrItem[String]],
  offensiveColdModifier: Option[ListOrItem[BigDecimal]],
  offensiveFreezeMax: Option[ListOrItem[BigDecimal]],
  offensiveConfusionChance: Option[ListOrItem[BigDecimal]],
  characterDefensiveAbility: Option[ListOrItem[BigDecimal]],
  offensiveTotalResistanceReductionAbsoluteMin: Option[ListOrItem[BigDecimal]],
  characterLifeModifier: Option[ListOrItem[BigDecimal]],
  skillActiveDuration: Option[ListOrItem[BigDecimal]],
  offensiveColdMax: Option[ListOrItem[BigDecimal]],
  defensiveProtectionModifier: Option[ListOrItem[BigDecimal]],
  offensiveChaosMax: Option[ListOrItem[BigDecimal]],
  offensiveSlowFireMin: Option[ListOrItem[BigDecimal]],
  defensiveBlockAmountModifier: Option[ListOrItem[BigDecimal]],
  defensivePoison: Option[ListOrItem[BigDecimal]],
  offensiveFireModifier: Option[ListOrItem[BigDecimal]],
  characterLifeRegen: Option[ListOrItem[BigDecimal]],
  skillCooldownTime: Option[ListOrItem[BigDecimal]],
  offensivePhysicalModifier: Option[ListOrItem[BigDecimal]],
  defensivePierce: Option[ListOrItem[BigDecimal]],
  offensiveTotalDamageReductionPercentDurationMin: Option[ListOrItem[BigDecimal]],
  racialBonusRace: Option[ListOrItem[String]],
  offensiveSlowOffensiveAbilityMin: Option[ListOrItem[BigDecimal]],
  offensiveSlowBleedingDurationMin: Option[ListOrItem[BigDecimal]],
  offensiveSlowLifeModifier: Option[ListOrItem[BigDecimal]],
  offensiveSlowColdMin: Option[ListOrItem[BigDecimal]],
  retaliationFireMin: Option[ListOrItem[BigDecimal]],
  offensivePoisonModifier: Option[ListOrItem[BigDecimal]],
  offensiveSlowPoisonModifier: Option[ListOrItem[BigDecimal]],
  offensiveLightningModifier: Option[ListOrItem[BigDecimal]],
  retaliationPoisonMin: Option[ListOrItem[BigDecimal]],
  warmUpEffectAttachPoint: Option[ListOrItem[String]],
  characterEnergyAbsorptionPercent: Option[ListOrItem[BigDecimal]],
  skillChanceWeight: Option[ListOrItem[BigDecimal]],
  characterLifeRegenModifier: Option[ListOrItem[BigDecimal]],
  offensiveStunMin: Option[ListOrItem[BigDecimal]],
  offensivePierceMin: Option[ListOrItem[BigDecimal]],
  offensiveKnockdownMin: Option[ListOrItem[BigDecimal]],
  offensiveSlowLifeMin: Option[ListOrItem[BigDecimal]],
  characterManaRegen: Option[ListOrItem[BigDecimal]],
  offensiveFearMin: Option[ListOrItem[BigDecimal]],
  sparkMaxNumber: Option[ListOrItem[BigDecimal]],
  projectileFragmentsLaunchNumberMin: Option[ListOrItem[BigDecimal]],
  characterDeflectProjectile: Option[ListOrItem[BigDecimal]],
  characterRunSpeedModifier: Option[ListOrItem[BigDecimal]],
  offensiveAetherMin: Option[ListOrItem[BigDecimal]],
  characterSpellCastSpeedModifier: Option[ListOrItem[BigDecimal]],
  characterDodgePercent: Option[ListOrItem[BigDecimal]],
  skillTargetRadius: Option[ListOrItem[BigDecimal]],
  offensiveSlowManaLeachDurationMin: Option[ListOrItem[BigDecimal]],
  characterDefensiveAbilityModifier: Option[ListOrItem[BigDecimal]],
  offensiveSlowPhysicalDurationMin: Option[ListOrItem[BigDecimal]],
  projectilePiercingChance: Option[ListOrItem[BigDecimal]],
  characterManaLimitReserve: Option[ListOrItem[BigDecimal]],
  offensiveChaosModifier: Option[ListOrItem[BigDecimal]],
  offensiveConfusionMin: Option[ListOrItem[BigDecimal]],
  skillLifeBonus: Option[ListOrItem[BigDecimal]],
  offensivePoisonMin: Option[ListOrItem[BigDecimal]],
  retaliationTotalDamageModifier: Option[ListOrItem[BigDecimal]],
  spawnObjectsTimeToLive: Option[ListOrItem[BigDecimal]],
  defensiveChaos: Option[ListOrItem[BigDecimal]],
  offensiveTotalDamageModifier: Option[ListOrItem[BigDecimal]],
  offensivePercentCurrentLifeMin: Option[ListOrItem[BigDecimal]],
  offensiveTotalResistanceReductionPercentMin: Option[ListOrItem[BigDecimal]],
  offensiveKnockdownMax: Option[ListOrItem[BigDecimal]],
  damageAbsorption: Option[ListOrItem[BigDecimal]],
  offensiveSlowFireModifier: Option[ListOrItem[BigDecimal]],
  offensiveLifeLeechMin: Option[ListOrItem[BigDecimal]],
  skillManaCost: Option[ListOrItem[BigDecimal]],
  offensiveSlowPoisonMin: Option[ListOrItem[BigDecimal]],
  conversionInType: Option[ListOrItem[String]],
  damageAbsorptionPercent: Option[ListOrItem[BigDecimal]]
)
object itemSkills_1 {
  implicit val codecJson: Codec.AsObject[itemSkills_1] = deriveCodec
}

case class itemSkills_2(
  offensiveSlowColdXOR: Option[BigDecimal],
  aetherDamageQualifier: Option[BigDecimal],
  useDelayTime: Option[BigDecimal],
  offensivePierceRatioModifier: Option[BigDecimal],
  skillProjectileNumber: Option[BigDecimal],
  characterIncreasedExperience: Option[BigDecimal],
  bleedingDamageQualifier: Option[BigDecimal],
  offensivePetrifyGlobal: Option[BigDecimal],
  waveDistance: Option[BigDecimal],
  defensiveColdDuration: Option[BigDecimal],
  skillCooldownReduction: Option[BigDecimal],
  refreshTime: Option[BigDecimal],
  defensiveLightningDuration: Option[BigDecimal],
  offensiveSlowRunSpeedDurationMin: Option[BigDecimal],
  retaliationLightningModifier: Option[BigDecimal],
  offensiveTotalResistanceReductionPercentDurationMin: Option[BigDecimal],
  offensiveTrapMin: Option[BigDecimal],
  Mace2h: Option[BigDecimal],
  stunChance: Option[BigDecimal],
  fxPakRandOffsetY: Option[BigDecimal],
  offensiveSlowDefensiveAbilityGlobal: Option[BigDecimal],
  dualWieldOnly: Option[BigDecimal],
  offensiveSlowPoisonDurationMin: Option[BigDecimal],
  defensiveTotalSpeedResistance: Option[BigDecimal],
  characterHealIncreasePercent: Option[BigDecimal],
  retaliationFireMax: Option[List[Int]],
  defensiveFreeze: Option[BigDecimal],
  skillDisplayName: Option[String],
  skillAllowsWarmUp: Option[BigDecimal],
  passThrough: Option[BigDecimal],
  defensiveBlockModifier: Option[BigDecimal],
  offensiveSlowFireXOR: Option[BigDecimal],
  retaliationSlowPoisonDurationMin: Option[BigDecimal],
  offensiveTrapMax: Option[BigDecimal],
  buffSkillName: Option[String],
  skillChargeTimeRanged: Option[BigDecimal],
  fxPakRandAngle: Option[BigDecimal],
  offensiveSlowColdDurationModifier: Option[BigDecimal],
  Scepter: Option[BigDecimal],
  offensiveSlowFireChance: Option[BigDecimal],
  fxPakExtents: Option[BigDecimal],
  offensiveSlowLifeDurationMin: Option[BigDecimal],
  sparkChance: Option[BigDecimal],
  targetFxFirstOnly: Option[BigDecimal],
  characterStrengthModifier: Option[List[Int]],
  Mace: Option[BigDecimal],
  Shield: Option[BigDecimal],
  conversionPercentage: Option[BigDecimal],
  offensiveSlowTotalSpeedChance: Option[BigDecimal],
  retaliationColdMin: Option[BigDecimal],
  pointBlank: Option[BigDecimal],
  defensiveLightning: Option[BigDecimal],
  fxPakRandOffsetX: Option[BigDecimal],
  offensiveSlowLightningChance: Option[BigDecimal],
  trackerOverride: Option[String],
  offensivePercentCurrentLifeMax: Option[BigDecimal],
  dualRangedOrRanged2hOnly: Option[BigDecimal],
  retaliationPhysicalMin: Option[BigDecimal],
  offensiveSlowOffensiveAbilityDurationMin: Option[BigDecimal],
  endWidth: Option[BigDecimal],
  numProjectiles: Option[BigDecimal],
  offensiveSlowLifeMax: Option[BigDecimal],
  offensiveSlowAttackSpeedMin: Option[BigDecimal],
  offensiveSlowOffensiveAbilityChance: Option[BigDecimal],
  offensiveSlowFireGlobal: Option[BigDecimal],
  offensiveSlowColdGlobal: Option[BigDecimal],
  offensiveSlowPoisonDurationModifier: Option[BigDecimal],
  defensiveCold: Option[BigDecimal],
  defensivePercentReflectionResistance: Option[BigDecimal],
  stunDuration: Option[BigDecimal],
  offensiveSlowTotalSpeedDurationMin: Option[BigDecimal],
  defensiveProtection: Option[List[Int]],
  endRadiusMultiplier: Option[BigDecimal],
  characterManaModifier: Option[BigDecimal],
  defensiveSleep: Option[BigDecimal],
  retaliationElementalMin: Option[BigDecimal],
  offensiveChaosModifierChance: Option[BigDecimal],
  conversionPercentage2: Option[BigDecimal],
  offensiveSlowLightningGlobal: Option[BigDecimal],
  fxPakSpawnDistance: Option[BigDecimal],
  offensiveSlowOffensiveAbilityGlobal: Option[BigDecimal],
  racialBonusPercentDefense: Option[BigDecimal],
  offensivePetrifyChance: Option[BigDecimal],
  offensiveConvertMin: Option[BigDecimal],
  maxMoveRatio: Option[BigDecimal],
  offensiveSlowDefensiveAbilityChance: Option[BigDecimal],
  defensiveBleedingDuration: Option[BigDecimal],
  pierceDamageQualifier: Option[BigDecimal],
  skillDownBitmapName: Option[String],
  offensiveSlowFireDurationModifier: Option[BigDecimal],
  defensiveFireDuration: Option[BigDecimal],
  poisonDamageQualifier: Option[BigDecimal],
  skillUpBitmapName: Option[String],
  defensiveLife: Option[BigDecimal],
  offensiveTotalResistanceReductionAbsoluteGlobal: Option[BigDecimal],
  retaliationAetherMin: Option[BigDecimal],
  retaliationSlowPhysicalDurationMin: Option[BigDecimal],
  skillMaxLevel: Option[BigDecimal],
  defensiveStun: Option[BigDecimal],
  skillManaBonus: Option[List[Int]],
  retaliationSlowAttackSpeedDurationMin: Option[BigDecimal],
  defensiveBleeding: Option[BigDecimal],
  achievementTracking: Option[BigDecimal],
  petBonusName: Option[String],
  elementalDamageQualifier: Option[BigDecimal],
  skillChargeMultipliers: Option[List[Int]],
  skillActiveManaCost: Option[BigDecimal],
  Ranged1h: Option[BigDecimal],
  shieldNoRanged: Option[BigDecimal],
  o: Option[String],
  offensiveSlowDefensiveAbilityXOR: Option[BigDecimal],
  defensiveLifeDuration: Option[BigDecimal],
  offensiveSlowLightningMax: Option[List[Int]],
  offensiveLifeMin: Option[ListOrItem[BigDecimal]],
  retaliationLightningMax: Option[ListOrItem[BigDecimal]],
  offensiveChaosMin: Option[ListOrItem[BigDecimal]],
  offensiveSlowPhysicalMin: Option[ListOrItem[BigDecimal]],
  skillLifePercent: Option[ListOrItem[BigDecimal]],
  offensiveElementalMin: Option[ListOrItem[BigDecimal]],
  offensiveFumbleMin: Option[ListOrItem[BigDecimal]],
  offensiveSlowPhysicalModifier: Option[ListOrItem[BigDecimal]],
  projectileFragmentsLaunchNumberMax: Option[ListOrItem[BigDecimal]],
  retaliationSlowPoisonMin: Option[ListOrItem[BigDecimal]],
  offensiveSlowTotalSpeedMin: Option[ListOrItem[BigDecimal]],
  petLimit: Option[ListOrItem[BigDecimal]],
  weaponDamagePct: Option[ListOrItem[BigDecimal]],
  conversionOutType: Option[ListOrItem[String]],
  defensivePhysical: Option[ListOrItem[BigDecimal]],
  offensiveSlowColdDurationMin: Option[ListOrItem[BigDecimal]],
  offensiveElementalMax: Option[ListOrItem[BigDecimal]],
  offensiveSlowBleedingMin: Option[ListOrItem[BigDecimal]],
  offensivePhysicalMax: Option[ListOrItem[BigDecimal]],
  skillTargetAngle: Option[ListOrItem[BigDecimal]],
  offensiveSlowDefensiveAbilityMin: Option[ListOrItem[BigDecimal]],
  characterManaRegenModifier: Option[ListOrItem[BigDecimal]],
  skillConnectionOn: Option[ListOrItem[String]],
  offensiveElementalModifier: Option[ListOrItem[BigDecimal]],
  offensiveColdMin: Option[ListOrItem[BigDecimal]],
  offensiveProjectileFumbleDurationMin: Option[ListOrItem[BigDecimal]],
  retaliationDamagePct: Option[ListOrItem[BigDecimal]],
  projectileLaunchNumber: Option[ListOrItem[BigDecimal]],
  characterTotalSpeedModifier: Option[ListOrItem[BigDecimal]],
  offensivePhysicalMin: Option[ListOrItem[BigDecimal]],
  retaliationLightningMin: Option[ListOrItem[BigDecimal]],
  characterAttackSpeedModifier: Option[ListOrItem[BigDecimal]],
  offensiveSlowColdModifier: Option[ListOrItem[BigDecimal]],
  offensiveAetherModifier: Option[ListOrItem[BigDecimal]],
  characterOffensiveAbility: Option[ListOrItem[BigDecimal]],
  offensiveTauntMin: Option[ListOrItem[BigDecimal]],
  skillManaPercent: Option[ListOrItem[BigDecimal]],
  lifeMonitorPercent: Option[ListOrItem[BigDecimal]],
  offensiveTrapChance: Option[ListOrItem[BigDecimal]],
  skillTargetNumber: Option[ListOrItem[BigDecimal]],
  petBurstSpawn: Option[ListOrItem[BigDecimal]],
  conversionInType2: Option[ListOrItem[String]],
  offensiveSlowLightningModifier: Option[ListOrItem[BigDecimal]],
  offensiveLightningMin: Option[ListOrItem[BigDecimal]],
  offensivePierceModifier: Option[ListOrItem[BigDecimal]],
  characterDefensiveBlockRecoveryReduction: Option[ListOrItem[BigDecimal]],
  offensiveLifeMax: Option[ListOrItem[BigDecimal]],
  characterOffensiveAbilityModifier: Option[ListOrItem[BigDecimal]],
  offensiveAetherMax: Option[ListOrItem[BigDecimal]],
  skillConnectionOff: Option[ListOrItem[String]],
  offensiveFumbleDurationMin: Option[ListOrItem[BigDecimal]],
  offensiveTotalResistanceReductionAbsoluteDurationMin: Option[ListOrItem[BigDecimal]],
  offensiveSlowBleedingModifier: Option[ListOrItem[BigDecimal]],
  offensiveTotalDamageReductionPercentMin: Option[ListOrItem[BigDecimal]],
  offensiveCritDamageModifier: Option[ListOrItem[BigDecimal]],
  defensiveElementalResistance: Option[ListOrItem[BigDecimal]],
  offensiveLightningMax: Option[ListOrItem[BigDecimal]],
  skillActiveLifeCost: Option[ListOrItem[BigDecimal]]
)
object itemSkills_2 {
  implicit val codecJson: Codec.AsObject[itemSkills_2] = deriveCodec
}

case class itemSkills_compat(item1: itemSkills_1, item2: itemSkills_2)
object itemSkills_compat {
  val encodeJson: Encoder.AsObject[itemSkills_compat] = {
    val enc1: Encoder.AsObject[itemSkills_1] = implicitly
    val enc2: Encoder.AsObject[itemSkills_2] = implicitly
    Encoder.AsObject.instance { a =>
      val t1 = enc1.encodeObject(a.item1)
      val t2 = enc2.encodeObject(a.item2)
      io.circe.JsonObject.fromIterable(t1.toVector ++ t2.toVector)
    }
  }

  val decodeJson: Decoder[itemSkills_compat] = {
    val dec1: Decoder[itemSkills_1] = implicitly
    val dec2: Decoder[itemSkills_2] = implicitly
    Decoder.instance { a =>
      for {
        x1 <- a.as[itemSkills_1](dec1)
        x2 <- a.as[itemSkills_2](dec2)
      } yield itemSkills_compat(item1 = x1, item2 = x2)
    }
  }

  implicit val codecJson: Codec[itemSkills_compat] = Codec.from(decodeJson, encodeJson.mapJson(_.dropNullValues))
}
