package gdfumo

import io.circe.{Codec, Decoder, Encoder}
import io.circe.generic.JsonCodec
import io.circe.generic.semiauto.deriveCodec
import datatype.{GDArray, StringOrElse}

case class itemSkills_1(
  templateName: String,
  l: Option[String],
  offensiveSlowPoisonChance: Option[BigDecimal],
  timeBetweenAttacks: Option[BigDecimal],
  offensiveSlowColdChance: Option[BigDecimal],
  retaliationSlowPhysicalMin: Option[List[Int]],
  offensiveSlowManaLeachMin: Option[List[Int]],
  retaliationChaosMax: Option[List[Int]],
  retaliationLifeMin: Option[List[Int]],
  spawnObjects: Option[spawnObjects],
  retaliationStunChance: Option[List[Int]],
  racialBonusAbsoluteDamage: Option[List[Int]],
  retaliationLifeMax: Option[List[Int]],
  retaliationChaosMin: Option[List[Int]],
  petSkillName: Option[petSkillName],
  offensivePhysicalChance: Option[List[Int]],
  dualRangedOnly: Option[BigDecimal],
  skillManaCostReduction: Option[BigDecimal],
  duration: Option[BigDecimal],
  projectileUsesAllDamage: Option[BigDecimal],
  onHitActivationChance: Option[BigDecimal],
  Sword: Option[BigDecimal],
  retaliationSlowAttackSpeedMin: Option[BigDecimal],
  offensiveElementalResistanceReductionPercentDurationMin: Option[BigDecimal],
  retaliationFireModifier: Option[BigDecimal],
  Ranged2h: Option[BigDecimal],
  offensivePetrifyMin: Option[BigDecimal],
  offensiveStunMax: Option[BigDecimal],
  offensiveSlowTotalSpeedGlobal: Option[BigDecimal],
  defensivePoisonDuration: Option[BigDecimal],
  skillBaseDescription: Option[String],
  racialBonusPercentDamage: Option[BigDecimal],
  offensiveDamageMultModifier: Option[BigDecimal],
  lifeDamageQualifier: Option[BigDecimal],
  thresholdDuration: Option[BigDecimal],
  canUseWhileMoving: Option[BigDecimal],
  retaliationDamageMultModifier: Option[BigDecimal],
  offensivePetrifyXOR: Option[BigDecimal],
  skillTier: Option[BigDecimal],
  cooldownTime: Option[BigDecimal],
  Axe2h: Option[BigDecimal],
  isPetDisplayable: Option[BigDecimal],
  skillChargeLevel: Option[BigDecimal],
  defensiveFire: Option[BigDecimal],
  offensiveGlobalChance: Option[BigDecimal],
  Dagger: Option[BigDecimal],
  defensiveAetherMaxResist: Option[BigDecimal],
  defensivePetrify: Option[BigDecimal],
  offensiveFreezeMin: Option[BigDecimal],
  offensiveSlowLifeDurationModifier: Option[BigDecimal],
  defensiveLightningMaxResist: Option[BigDecimal],
  defensiveTrap: Option[BigDecimal],
  offensiveSlowAttackSpeedDurationMin: Option[BigDecimal],
  defensiveLifeMaxResist: Option[BigDecimal],
  offensiveSlowLightningXOR: Option[BigDecimal],
  useResetsDuration: Option[BigDecimal],
  offensiveColdModifierChance: Option[BigDecimal],
  offensiveSlowPhysicalDurationModifier: Option[BigDecimal],
  defensiveDisruption: Option[BigDecimal],
  dualRangedOrAllRangedOnly: Option[BigDecimal],
  retaliationPhysicalModifier: Option[BigDecimal],
  defensiveFireMaxResist: Option[BigDecimal],
  racialBonusAbsoluteDefense: Option[BigDecimal],
  projectilePeriod: Option[BigDecimal],
  Offhand: Option[BigDecimal],
  defensiveSlowLifeLeach: Option[BigDecimal],
  offensiveSlowRunSpeedMin: Option[BigDecimal],
  offensiveElementalChance: Option[BigDecimal],
  petPadding: Option[BigDecimal],
  projectilePiercing: Option[BigDecimal],
  offensiveElementalResistanceReductionPercentMin: Option[BigDecimal],
  retaliationFearMin: Option[BigDecimal],
  startWidth: Option[BigDecimal],
  waveSource: Option[String],
  beamThickness: Option[BigDecimal],
  stunPeriod: Option[BigDecimal],
  defensiveChaosMaxResist: Option[BigDecimal],
  Spear2h: Option[BigDecimal],
  Axe: Option[BigDecimal],
  overwriteBaseSkill: Option[BigDecimal],
  sparkGap: Option[BigDecimal],
  offensiveFreezeChance: Option[BigDecimal],
  retaliationPoisonModifier: Option[BigDecimal],
  trackSpawns: Option[BigDecimal],
  offensiveSlowOffensiveAbilityXOR: Option[BigDecimal],
  defensiveColdMaxResist: Option[BigDecimal],
  offensiveSlowLightningDurationModifier: Option[BigDecimal],
  fxPakAlternate: Option[BigDecimal],
  offensiveSlowTotalSpeedXOR: Option[BigDecimal],
  maxRange: Option[BigDecimal],
  offensiveConfusionMax: Option[BigDecimal],
  offensiveAetherModifierChance: Option[BigDecimal],
  offensiveTotalResistanceReductionAbsoluteChance: Option[BigDecimal],
  explosionRadius: Option[BigDecimal],
  offensiveSlowLightningDurationMin: Option[BigDecimal],
  retaliationFreezeMin: Option[BigDecimal],
  characterMana: Option[BigDecimal],
  chaosDamageQualifier: Option[BigDecimal],
  characterLife: Option[BigDecimal],
  retaliationStunMin: Option[BigDecimal],
  delayMovement: Option[BigDecimal],
  skillChargeDuration: Option[BigDecimal],
  skillChargeTime: Option[BigDecimal],
  physicalDamageQualifier: Option[BigDecimal],
  defensiveAether: Option[BigDecimal],
  skillCooldownReductionChance: Option[BigDecimal],
  Sword2h: Option[BigDecimal],
  skillUltimateLevel: Option[BigDecimal],
  offensiveSlowBleedingDurationModifier: Option[BigDecimal],
  offensiveFireMax: GDArray[BigDecimal],
  projectileLaunchRotation: GDArray[BigDecimal],
  projectileExplosionRadius: GDArray[BigDecimal],
  offensiveSlowLightningMin: GDArray[BigDecimal],
  offensiveSlowFireDurationMin: GDArray[BigDecimal],
  offensivePierceMax: GDArray[BigDecimal],
  offensiveLifeModifier: GDArray[BigDecimal],
  defensivePercentCurrentLife: GDArray[BigDecimal],
  offensiveProjectileFumbleMin: GDArray[BigDecimal],
  offensiveSlowDefensiveAbilityDurationMin: GDArray[BigDecimal],
  offensiveFireMin: GDArray[BigDecimal],
  offensiveStunChance: GDArray[BigDecimal],
  offensivePoisonMax: GDArray[BigDecimal],
  conversionOutType2: GDArray[String],
  offensiveColdModifier: GDArray[BigDecimal],
  offensiveFreezeMax: GDArray[BigDecimal],
  offensiveConfusionChance: GDArray[BigDecimal],
  characterDefensiveAbility: GDArray[BigDecimal],
  offensiveTotalResistanceReductionAbsoluteMin: GDArray[BigDecimal],
  characterLifeModifier: GDArray[BigDecimal],
  skillActiveDuration: GDArray[BigDecimal],
  offensiveColdMax: GDArray[BigDecimal],
  defensiveProtectionModifier: GDArray[BigDecimal],
  offensiveChaosMax: GDArray[BigDecimal],
  offensiveSlowFireMin: GDArray[BigDecimal],
  defensiveBlockAmountModifier: GDArray[BigDecimal],
  defensivePoison: GDArray[BigDecimal],
  offensiveFireModifier: GDArray[BigDecimal],
  characterLifeRegen: GDArray[BigDecimal],
  skillCooldownTime: GDArray[BigDecimal],
  offensivePhysicalModifier: GDArray[BigDecimal],
  defensivePierce: GDArray[BigDecimal],
  offensiveTotalDamageReductionPercentDurationMin: GDArray[BigDecimal],
  racialBonusRace: GDArray[String],
  offensiveSlowOffensiveAbilityMin: GDArray[BigDecimal],
  offensiveSlowBleedingDurationMin: GDArray[BigDecimal],
  offensiveSlowLifeModifier: GDArray[BigDecimal],
  offensiveSlowColdMin: GDArray[BigDecimal],
  retaliationFireMin: GDArray[BigDecimal],
  offensivePoisonModifier: GDArray[BigDecimal],
  offensiveSlowPoisonModifier: GDArray[BigDecimal],
  offensiveLightningModifier: GDArray[BigDecimal],
  retaliationPoisonMin: GDArray[BigDecimal],
  warmUpEffectAttachPoint: GDArray[String],
  characterEnergyAbsorptionPercent: GDArray[BigDecimal],
  skillChanceWeight: GDArray[BigDecimal],
  characterLifeRegenModifier: GDArray[BigDecimal],
  offensiveStunMin: GDArray[BigDecimal],
  offensivePierceMin: GDArray[BigDecimal],
  offensiveKnockdownMin: GDArray[BigDecimal],
  offensiveSlowLifeMin: GDArray[BigDecimal],
  characterManaRegen: GDArray[BigDecimal],
  offensiveFearMin: GDArray[BigDecimal],
  sparkMaxNumber: GDArray[BigDecimal],
  projectileFragmentsLaunchNumberMin: GDArray[BigDecimal],
  characterDeflectProjectile: GDArray[BigDecimal],
  characterRunSpeedModifier: GDArray[BigDecimal],
  offensiveAetherMin: GDArray[BigDecimal],
  characterSpellCastSpeedModifier: GDArray[BigDecimal],
  characterDodgePercent: GDArray[BigDecimal],
  skillTargetRadius: GDArray[BigDecimal],
  offensiveSlowManaLeachDurationMin: GDArray[BigDecimal],
  characterDefensiveAbilityModifier: GDArray[BigDecimal],
  offensiveSlowPhysicalDurationMin: GDArray[BigDecimal],
  projectilePiercingChance: GDArray[BigDecimal],
  characterManaLimitReserve: GDArray[BigDecimal],
  offensiveChaosModifier: GDArray[BigDecimal],
  offensiveConfusionMin: GDArray[BigDecimal],
  skillLifeBonus: GDArray[BigDecimal],
  offensivePoisonMin: GDArray[BigDecimal],
  retaliationTotalDamageModifier: GDArray[BigDecimal],
  spawnObjectsTimeToLive: GDArray[BigDecimal],
  defensiveChaos: GDArray[BigDecimal],
  offensiveTotalDamageModifier: GDArray[BigDecimal],
  offensivePercentCurrentLifeMin: GDArray[BigDecimal],
  offensiveTotalResistanceReductionPercentMin: GDArray[BigDecimal],
  offensiveKnockdownMax: GDArray[BigDecimal],
  damageAbsorption: GDArray[BigDecimal],
  offensiveSlowFireModifier: GDArray[BigDecimal],
  offensiveLifeLeechMin: GDArray[BigDecimal],
  skillManaCost: GDArray[BigDecimal],
  offensiveSlowPoisonMin: GDArray[BigDecimal],
  conversionInType: GDArray[String],
  damageAbsorptionPercent: GDArray[BigDecimal]
)
object itemSkills_1 {
  implicit val codecJson: Codec.AsObject[itemSkills_1] = deriveCodec
}

case class itemSkills_2(
  offensiveSlowColdXOR: Option[BigDecimal],
  aetherDamageQualifier: Option[BigDecimal],
  useDelayTime: Option[BigDecimal],
  offensivePierceRatioModifier: Option[BigDecimal],
  skillProjectileNumber: Option[BigDecimal],
  characterIncreasedExperience: Option[BigDecimal],
  bleedingDamageQualifier: Option[BigDecimal],
  offensivePetrifyGlobal: Option[BigDecimal],
  waveDistance: Option[BigDecimal],
  defensiveColdDuration: Option[BigDecimal],
  skillCooldownReduction: Option[BigDecimal],
  refreshTime: Option[BigDecimal],
  defensiveLightningDuration: Option[BigDecimal],
  offensiveSlowRunSpeedDurationMin: Option[BigDecimal],
  retaliationLightningModifier: Option[BigDecimal],
  offensiveTotalResistanceReductionPercentDurationMin: Option[BigDecimal],
  offensiveTrapMin: Option[BigDecimal],
  Mace2h: Option[BigDecimal],
  stunChance: Option[BigDecimal],
  fxPakRandOffsetY: Option[BigDecimal],
  offensiveSlowDefensiveAbilityGlobal: Option[BigDecimal],
  dualWieldOnly: Option[BigDecimal],
  offensiveSlowPoisonDurationMin: Option[BigDecimal],
  defensiveTotalSpeedResistance: Option[BigDecimal],
  characterHealIncreasePercent: Option[BigDecimal],
  retaliationFireMax: Option[List[Int]],
  defensiveFreeze: Option[BigDecimal],
  skillDisplayName: Option[String],
  skillAllowsWarmUp: Option[BigDecimal],
  passThrough: Option[BigDecimal],
  defensiveBlockModifier: Option[BigDecimal],
  offensiveSlowFireXOR: Option[BigDecimal],
  retaliationSlowPoisonDurationMin: Option[BigDecimal],
  offensiveTrapMax: Option[BigDecimal],
  buffSkillName: Option[String],
  skillChargeTimeRanged: Option[BigDecimal],
  fxPakRandAngle: Option[BigDecimal],
  offensiveSlowColdDurationModifier: Option[BigDecimal],
  Scepter: Option[BigDecimal],
  offensiveSlowFireChance: Option[BigDecimal],
  fxPakExtents: Option[BigDecimal],
  offensiveSlowLifeDurationMin: Option[BigDecimal],
  sparkChance: Option[BigDecimal],
  targetFxFirstOnly: Option[BigDecimal],
  characterStrengthModifier: Option[List[Int]],
  Mace: Option[BigDecimal],
  Shield: Option[BigDecimal],
  conversionPercentage: Option[BigDecimal],
  offensiveSlowTotalSpeedChance: Option[BigDecimal],
  retaliationColdMin: Option[BigDecimal],
  pointBlank: Option[BigDecimal],
  defensiveLightning: Option[BigDecimal],
  fxPakRandOffsetX: Option[BigDecimal],
  offensiveSlowLightningChance: Option[BigDecimal],
  trackerOverride: Option[String],
  offensivePercentCurrentLifeMax: Option[BigDecimal],
  dualRangedOrRanged2hOnly: Option[BigDecimal],
  retaliationPhysicalMin: Option[BigDecimal],
  offensiveSlowOffensiveAbilityDurationMin: Option[BigDecimal],
  endWidth: Option[BigDecimal],
  numProjectiles: Option[BigDecimal],
  offensiveSlowLifeMax: Option[BigDecimal],
  offensiveSlowAttackSpeedMin: Option[BigDecimal],
  offensiveSlowOffensiveAbilityChance: Option[BigDecimal],
  offensiveSlowFireGlobal: Option[BigDecimal],
  offensiveSlowColdGlobal: Option[BigDecimal],
  offensiveSlowPoisonDurationModifier: Option[BigDecimal],
  defensiveCold: Option[BigDecimal],
  defensivePercentReflectionResistance: Option[BigDecimal],
  stunDuration: Option[BigDecimal],
  offensiveSlowTotalSpeedDurationMin: Option[BigDecimal],
  defensiveProtection: Option[List[Int]],
  endRadiusMultiplier: Option[BigDecimal],
  characterManaModifier: Option[BigDecimal],
  defensiveSleep: Option[BigDecimal],
  retaliationElementalMin: Option[BigDecimal],
  offensiveChaosModifierChance: Option[BigDecimal],
  conversionPercentage2: Option[BigDecimal],
  offensiveSlowLightningGlobal: Option[BigDecimal],
  fxPakSpawnDistance: Option[BigDecimal],
  offensiveSlowOffensiveAbilityGlobal: Option[BigDecimal],
  racialBonusPercentDefense: Option[BigDecimal],
  offensivePetrifyChance: Option[BigDecimal],
  offensiveConvertMin: Option[BigDecimal],
  maxMoveRatio: Option[BigDecimal],
  offensiveSlowDefensiveAbilityChance: Option[BigDecimal],
  defensiveBleedingDuration: Option[BigDecimal],
  pierceDamageQualifier: Option[BigDecimal],
  skillDownBitmapName: Option[String],
  offensiveSlowFireDurationModifier: Option[BigDecimal],
  defensiveFireDuration: Option[BigDecimal],
  poisonDamageQualifier: Option[BigDecimal],
  skillUpBitmapName: Option[String],
  defensiveLife: Option[BigDecimal],
  offensiveTotalResistanceReductionAbsoluteGlobal: Option[BigDecimal],
  retaliationAetherMin: Option[BigDecimal],
  retaliationSlowPhysicalDurationMin: Option[BigDecimal],
  skillMaxLevel: Option[BigDecimal],
  defensiveStun: Option[BigDecimal],
  skillManaBonus: Option[List[Int]],
  retaliationSlowAttackSpeedDurationMin: Option[BigDecimal],
  defensiveBleeding: Option[BigDecimal],
  achievementTracking: Option[BigDecimal],
  petBonusName: Option[String],
  elementalDamageQualifier: Option[BigDecimal],
  skillChargeMultipliers: Option[List[Int]],
  skillActiveManaCost: Option[BigDecimal],
  Ranged1h: Option[BigDecimal],
  shieldNoRanged: Option[BigDecimal],
  o: Option[String],
  offensiveSlowDefensiveAbilityXOR: Option[BigDecimal],
  defensiveLifeDuration: Option[BigDecimal],
  offensiveSlowLightningMax: Option[List[Int]],
  offensiveLifeMin: GDArray[BigDecimal],
  retaliationLightningMax: GDArray[BigDecimal],
  offensiveChaosMin: GDArray[BigDecimal],
  offensiveSlowPhysicalMin: GDArray[BigDecimal],
  skillLifePercent: GDArray[BigDecimal],
  offensiveElementalMin: GDArray[BigDecimal],
  offensiveFumbleMin: GDArray[BigDecimal],
  offensiveSlowPhysicalModifier: GDArray[BigDecimal],
  projectileFragmentsLaunchNumberMax: GDArray[BigDecimal],
  retaliationSlowPoisonMin: GDArray[BigDecimal],
  offensiveSlowTotalSpeedMin: GDArray[BigDecimal],
  petLimit: GDArray[BigDecimal],
  weaponDamagePct: GDArray[BigDecimal],
  conversionOutType: GDArray[String],
  defensivePhysical: GDArray[BigDecimal],
  offensiveSlowColdDurationMin: GDArray[BigDecimal],
  offensiveElementalMax: GDArray[BigDecimal],
  offensiveSlowBleedingMin: GDArray[BigDecimal],
  offensivePhysicalMax: GDArray[BigDecimal],
  skillTargetAngle: GDArray[BigDecimal],
  offensiveSlowDefensiveAbilityMin: GDArray[BigDecimal],
  characterManaRegenModifier: GDArray[BigDecimal],
  skillConnectionOn: GDArray[String],
  offensiveElementalModifier: GDArray[BigDecimal],
  offensiveColdMin: GDArray[BigDecimal],
  offensiveProjectileFumbleDurationMin: GDArray[BigDecimal],
  retaliationDamagePct: GDArray[BigDecimal],
  projectileLaunchNumber: GDArray[BigDecimal],
  characterTotalSpeedModifier: GDArray[BigDecimal],
  offensivePhysicalMin: GDArray[BigDecimal],
  retaliationLightningMin: GDArray[BigDecimal],
  characterAttackSpeedModifier: GDArray[BigDecimal],
  offensiveSlowColdModifier: GDArray[BigDecimal],
  offensiveAetherModifier: GDArray[BigDecimal],
  characterOffensiveAbility: GDArray[BigDecimal],
  offensiveTauntMin: GDArray[BigDecimal],
  skillManaPercent: GDArray[BigDecimal],
  lifeMonitorPercent: GDArray[BigDecimal],
  offensiveTrapChance: GDArray[BigDecimal],
  skillTargetNumber: GDArray[BigDecimal],
  petBurstSpawn: GDArray[BigDecimal],
  conversionInType2: GDArray[String],
  offensiveSlowLightningModifier: GDArray[BigDecimal],
  offensiveLightningMin: GDArray[BigDecimal],
  offensivePierceModifier: GDArray[BigDecimal],
  characterDefensiveBlockRecoveryReduction: GDArray[BigDecimal],
  offensiveLifeMax: GDArray[BigDecimal],
  characterOffensiveAbilityModifier: GDArray[BigDecimal],
  offensiveAetherMax: GDArray[BigDecimal],
  skillConnectionOff: GDArray[String],
  offensiveFumbleDurationMin: GDArray[BigDecimal],
  offensiveTotalResistanceReductionAbsoluteDurationMin: GDArray[BigDecimal],
  offensiveSlowBleedingModifier: GDArray[BigDecimal],
  offensiveTotalDamageReductionPercentMin: GDArray[BigDecimal],
  offensiveCritDamageModifier: GDArray[BigDecimal],
  defensiveElementalResistance: GDArray[BigDecimal],
  offensiveLightningMax: GDArray[BigDecimal],
  skillActiveLifeCost: GDArray[BigDecimal]
)
object itemSkills_2 {
  implicit val codecJson: Codec.AsObject[itemSkills_2] = deriveCodec
}

case class itemSkills_compat(item1: itemSkills_1, item2: itemSkills_2)
object itemSkills_compat {
  val encodeJson: Encoder.AsObject[itemSkills_compat] = {
    val enc1: Encoder.AsObject[itemSkills_1] = implicitly
    val enc2: Encoder.AsObject[itemSkills_2] = implicitly
    Encoder.AsObject.instance { a =>
      val t1 = enc1.encodeObject(a.item1)
      val t2 = enc2.encodeObject(a.item2)
      io.circe.JsonObject.fromIterable(t1.toVector ++ t2.toVector)
    }
  }

  val decodeJson: Decoder[itemSkills_compat] = {
    val dec1: Decoder[itemSkills_1] = implicitly
    val dec2: Decoder[itemSkills_2] = implicitly
    Decoder.instance { a =>
      for {
        x1 <- a.as[itemSkills_1](dec1)
        x2 <- a.as[itemSkills_2](dec2)
      } yield itemSkills_compat(item1 = x1, item2 = x2)
    }
  }

  implicit val codecJson: Codec[itemSkills_compat] = Codec.from(decodeJson, encodeJson.mapJson(_.dropNullValues))
}
